### ISSUE TITLE
Where can I enter the sender id of FCM?

### ISSUE THREAD

**Issue by yoshi-gift** [mercari/gaurun#68]
I sent
```
% curl \
    -H "Content-Type: application/json" \
    -X POST "http://localhost:1056/push" \
    -d '{"notifications": [ {"token":["token"],"platform":2,"message":"test"} ] }'
{"message":"ok"}
```

I got a "MismatchSenderId"
```
% bin/gaurun -c conf/gaurun.toml
{"level":"info","time":"2017/05/18 09:06:42 JST","message":"","type":"accepted-request","uri":"/push","method":"POST","proto":"HTTP/1.1","content_length":220}
{"level":"info","time":"2017/05/18 09:06:42 JST","message":"test","id":1,"platform":"android","token":"token","type":"accepted-push","ptime":0,"error":""}
{"level":"error","time":"2017/05/18 09:06:43 JST","message":"test","id":1,"platform":"android","token":"token","type":"failed-push","ptime":0.181,"error":"MismatchSenderId"}
```

conf/gaurun.toml
``` toml
[core]
port = "1056"
#port = "unix:/tmp/gaurun.sock"
workers = 8
queues = 8192
notification_max = 100
shutdown_timeout = 30

[android]
apikey = "api key"
enabled = true
timeout = 5 # sec
keepalive_timeout = 30
keepalive_conns = 4
retry_max = 1
use_fcm = true

[ios]
pem_cert_path = "cert.pem"
pem_key_path = "key.pem"
sandbox = true
enabled = false
timeout = 5
keepalive_timeout = 30
keepalive_conns = 6
retry_max = 1

[log]
access_log = "stdout"
error_log = "stderr"
level = "error"
```

Is something wrong?

Thank you,
